# This is a config for E2B sandbox template.
# You can use template ID (3qds6i7xe83q4y8ooo6u) or template name (vibe-nextjs-harsh-812) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-harsh-812") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-harsh-812") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-harsh-812')

team_id = "85d18320-f879-4b36-8645-b3202d6669a4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-harsh-812"
template_id = "3qds6i7xe83q4y8ooo6u"
